# Header
menu:
  Home: /sheldon.is.a.geek/
  ME: /sheldon.is.a.geek/2015/01/14/My-First-Post/
  Demo_Vdieo: /sheldon.is.a.geek/2015/03/01/-Raspberry-Pi-Demod-Video/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
